# Generated by Django 5.0.6 on 2024-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
